source "https://rubygems.org"
gemspec

gem "jekyll-github-metadata", ">= 2.15"

gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins

gem "html-proofer", "~> 5.0", :group => :development

gem 'jekyll-autolinks'

gem 'kramdown-parser-gfm'
gem "jekyll-remote-theme"

#------------------------------------------------------------------------------------------------
# After modifying the Gemfile:
#------------------------------------------------------------------------------------------------
#bundle install
#bundle exec jekyll serve
